services:
  - type: web
    name: waraq-ai-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 7860
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: WARAQAI_CLERK_SECRET_KEY
        sync: false
